### ISSUE TITLE
lattice2 shapestring

### ISSUE THREAD

**Issue by hisham-1465** [DeepSOIC/Lattice2#93]
lattice2 shapestring doesn't work in Freecad 1.0

**Comment by cibernakaq** [comment]
I got the same error..

Running the Python command 'Lattice2_ShapeString' failed:
Traceback (most recent call last):
  File "/home/johnroger/snap/freecad/common/Mod/lattice2/./lattice2ShapeString.py", line 298, in Activated
    CreateLatticeShapeString(name = "Strings")
  File "/home/johnroger/snap/freecad/common/Mod/lattice2/./lattice2ShapeString.py", line 273, in CreateLatticeShapeString
    FreeCADGui.doCommand("f = lattice2ShapeString.makeLatticeShapeString(name='"+name+"')")
  File "<string>", line 1, in <module>
  File "/home/johnroger/snap/freecad/common/Mod/lattice2/./lattice2ShapeString.py", line 77, in makeLatticeShapeString
    LatticeShapeString(obj)
  File "/home/johnroger/snap/freecad/common/Mod/lattice2/./lattice2ShapeString.py", line 106, in __init__
    self.makeFoolObj(obj)
  File "/home/johnroger/snap/freecad/common/Mod/lattice2/./lattice2ShapeString.py", line 143, in makeFoolObj
    self.draft_shape_string = _ShapeString(foolObj) 
  File "/snap/freecad/1202/usr/Mod/Draft/draftobjects/shapestring.py", line 48, in __init__
    self.set_properties(obj)
  File "/snap/freecad/1202/usr/Mod/Draft/draftobjects/shapestring.py", line 52, in set_properties
    properties = obj.PropertiesList

'FoolFeatureDocumentObject' object has no attribute 'PropertiesList' (6 times)

FreeCAD Details:

OS: Ubuntu Core 22 (ubuntu:GNOME/ubuntu/xcb)
Architecture: x86_64
Version: 1.0.0.38641 +468 (Git) Snap 1202
Build type: Release
Branch: tag: 1.0.0
Hash: 2fcc5317fe3aee96ca73475986a577719fc78e20
Python 3.10.12, Qt 5.15.10, Coin 4.0.0, Vtk 7.1.1, OCC 7.7.1
Locale: English/United States (en_US)

**Comment by pyro9** [comment]
Fixed in #96
